[project]
name = "cosmosdb-example"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiohttp>=3.13.3",
    "azure-cosmos>=4.9.0",
    "azure-identity>=1.19.0",
    "pydantic-settings>=2.7.0",
]
